ASSISTANT_NAME: Amadoo # Not customizable at the moment
WAKE_WORD: Amadou # Not customizable at the moment, should be in the lang dictionary and in kws files
ASSISTANT_PURPOSE: Cooking Assistant
RESPONSE_LANGUAGE: fr
USE_WHISPER_API: true
OPENAI_MODEL: gpt-4o
ENABLE_TTS: false
TTS_VOICE: "onyx" # Optional: Specify the default voice
